import 'package:flutter/material.dart';
import '../models/meal.dart';
import '../models/category.dart';

List<Category> MEAL_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Breakfast',
    color: Colors.redAccent,
  ),
  Category(
    id: 'c2',
    title: 'Lunch',
    color: Colors.yellow,
  ),
  Category(
    id: 'c3',
    title: 'Dinner',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'Dessert',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'Vegetarian',
    color: Colors.lightGreenAccent,
  ),
  Category(
    id: 'c6',
    title: 'Drinks',
    color: Colors.lightBlueAccent,
  ),
];

List<Meal> RECIPE_MEALS = const [

  // Breakfast List: 10 meals
  Meal(
    id: 'm1',
    categories: [
      'c1',
    ],
    title: 'Baked Eggs with Swiss Chard and Green Olives',
    affordability: Affordability.Affordable,
    complexity: Complexity.Advanced,
    /*imageUrl:
    'https://images.themodernproper.com/billowy-turkey/production/posts/2016/Baked-Eggs-with-Swiss-Chard-and-Green-Olives-14.jpg?w=1200&q=82&fm=jpg&fit=crop&dm=1601220209&s=07dba643896ff73c5908c21bb271aaba',*/
    imageUrl:
    'assets/m1.jpg',
    duration: 20,
    ingredients: [
      '4 thick bacon slices, cut into 1-inch pieces, optional',
      '1 Tbsp Extra virgin olive oil',
      '1/2 small yellow onion, diced, about 1/2 cup',
      '2 garlic cloves, minced',
      '4 cups roughly chopped Swiss chard leaves, stems removed, about 1 bunch',
      '1/2 cup pitted castelvetrano olives, pitted, sliced, plus more for garnish',
      '2/3 cup heavy cream',
      '4 eggs',
      '1 Tbsp salted butter or olive oil',
      '1/4 cup panko',
      '1/4 cup crumbled feta',
      '1/2 tsp flaky salt for finishing',
      '2 Tbsp minced chives for garnishing',
      '1 loaf of crusty bread, for serving',
    ],
    steps: [
      'Heat the oven to 425°F.',
      'In a medium sized ovenproof skillet, cook the bacon over medium heat. Transfer the bacon to a paper towel lined plate. Drain off all but 1 tablespoon of the bacon grease.',
      'Add 1 tablespoon of olive oil to the pan. Still over medium heat, add the onions, cooking until beginning to soften, about 5 minutes. Add the garlic and swiss chard, continuing to cook until the chard begins to wilt about 2-3 more minutes. Return the cooked bacon to the pan along with the olives. Remove from heat.',
      'Create 4 wells in the chard mixture. This is where you will crack the eggs. Once all of the eggs are in the wells you created, drizzle the entire dish with the cream. Place the dish in the oven and cook for 8-10 minutes. Just until the white parts of the eggs are no longer transparent, but the egg yolks are still runny.',
      'While the eggs are baking, melt the butter in a small skillet, over medium heat. Add the panko and toss to combine with the butter. Continue cooking and tossing until the panko is golden brown before removing from the heat.',
      'Remove the eggs from the oven and sprinkle the toasted panko over the entire dish. Sprinkle with the feta, extra olives (if desired), flaky salt and fresh chives.',
      'Serve alongside some good toasted bread.',

    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c1',
    ],
    title: 'Smoky Bacon Cheddar Breakfast Hash',
    affordability: Affordability.Affordable,
    complexity: Complexity.Intermediate,
    imageUrl:
    'assets/m2.jpg',
    duration: 15,
    ingredients: [
      '8 slices thick-cut bacon, diced',
      '2 tablespoons olive or vegetable oil, if needed',
      '2 russet potatoes (about 1½ pounds), cut into ½ -inch pieces',
      '1/2 yellow onion, diced',
      '1 large red bell pepper, diced',
      '1 cup heavy cream',
      '1 tablespoon Worcestershire sauce',
      '1/2 teaspoon smoked paprika',
      '1 teaspoon sea salt',
      '1/4 teaspoon freshly cracked black pepper',
      '1 cup shredded cheddar cheese',
      '1/4 cup green onions, chopped',
      '6 eggs, cooked to your liking',
      '6 slices crusty bread, toasted (optional)',
    ],
    steps: [
      'Heat a large nonstick or cast-iron skillet over medium-high heat. Add the bacon and cook until almost crispy and the fat has rendered, about 10 minutes. Using a slotted spoon, transfer the bacon to a paper towel-lined plate, reserving the fat in the pan. Discard all but ¼ cup of the bacon fat.',
      'Add the potatoes to the bacon fat in a single layer and cook until golden brown on mostly tender, 10-12 minutes. Add the onions and bell peppers and cook, about 5 minutes more.',
      'Return the bacon to the pan and stir in the cream, Worcestershire sauce, paprika, salt, and pepper. Reduce the heat to low and simmer until the cream has thickened, about 3 minutes.',
      'Remove the skillet from heat. Sprinkle the hash with cheddar and green onions.',
      'Spoon the hash out of the pan, dividing it evenly between plates. Top each with an egg and serve with toast on the side.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c1',
    ],
    title: 'Ham and Swiss Omelet',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m3.jpg',
    duration: 15,
    ingredients: [
      '1 tablespoon butter',
      '3 eggs',
      '3 tablespoons water',
      '1/8 teaspoon salt',
      '1/8 teaspoon pepper',
      '1/2 cup cubed fully cooked ham',
      '1/4 cup shredded Swiss cheese',
    ],
    steps: [
      'In a small nonstick skillet, melt butter over medium-high heat. Whisk the eggs, water, salt and pepper. Add egg mixture to skillet (mixture should set immediately at edges).',
      'As eggs set, push cooked edges toward the center, letting uncooked portion flow underneath. When the eggs are set, place ham on one side and sprinkle with cheese; fold other side over filling. Slide omelet onto a plate.',

    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c1',
    ],
    title: 'Feta Scrambled Egg Wraps',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m4.jpg',
    duration: 15,
    ingredients: [
      '1-1/2 cups Southwestern-style egg substitute',
      '3/4 cup crumbled feta cheese',
      '2 tablespoons sliced pepperoncini, chopped',
      '4 whole wheat tortillas (8 inches), warmed',
    ],
    steps: [
      'Place a large skillet coated with cooking spray over medium heat.',
      'Pour in egg substitute',
      'Cook and stir until thickened and no liquid egg remains.',
      'Gently stir in cheese and pepperoncini',
      'Heat through and serve in tortillas',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm5',
    categories: [
      'c1',
    ],
    title: 'Asian Vegetable and Noodle Omelettes',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m5.jpeg',
    duration: 20,
    ingredients: [
      '100g dried rice vermicelli noodles',
      '8 eggs',
      '2 green onions, finely chopped',
      '1 1/2 tea spoon vegetable oil',
      '2 garlic cloves, crushed',
      '2cm piece fresh ginger, peeled, finely grated',
      '1/2 x 800g packet frozen Shanghai stir-fry vegetable mix (contains carrot, broccoli, green beans, sugar snap peas, red onion, red capsicum and celery.)',
      '1 tea spoon Chang oyster sauce',
      '2 tea spoon sesame oil',
      '1 tea spoon soy sauce',

    ],
    steps: [
      'Place noodles in a heatproof bowl. Cover with boiling water. Stand for 4 to 5 minutes or until tender. Drain. Whisk eggs and onion in a bowl.',
      'Heat 2 teaspoons vegetable oil in a wok over high heat. Swirl to coat. Add garlic and ginger. Stir-fry for 1 minute. Add vegetable mix, oyster sauce and sesame oil. Stir-fry for 2 to 3 minutes or until vegetables are just tender. Transfer to a bowl. Add noodles. Toss to combine.',
      'Heat 1 teaspoon remaining vegetable oil in a 20cm non-stick frying pan over medium heat. Add one-quarter of the egg mixture. Swirl to coat. Cook for 30 seconds or until just set.',
      'Top 1 half of omelette with one-quarter of the vegetable mixture. Cook for 1 minute or until egg has set. Fold over to enclose filling. Slide onto a plate. Cover to keep warm. Repeat with remaining oil, egg mixture and vegetable mixture to make 4 omelettes. Serve drizzled with soy sauce.',

    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm6',
    categories: [
      'c1',
    ],
    title: 'Japanese Egg Salad Sandwich',
    affordability: Affordability.Affordable,
    complexity: Complexity.Intermediate,
    imageUrl:
    'assets/m6.jpg',
    duration: 55,
    ingredients: [

      '8 large eggs',
      '6 hard boiled eggs',
      '2 - 3 tbsp mayonnaise or kewpie mayonnaise',
      '1/2 tea spoon sugar',
      'Salt to taste',
      'White pepper to taste',
      '2 spring onions green parts, chopped finely',
      '8 slices of white sandwich bread brioche bread or Shokupan',
      'Dijon mustard',
      'Butter or extra mayonnaise',
      'Extra salt for seasoning',
      '2 soft boiled eggs',
    ],
    steps: [
      'Cut the two soft boiled eggs in half using a sharp knife. The yolks should be soft and jammy. Lightly season each of the halves with salt.',
      'Take two slices of bread. Trim the edges off the bread slices. I only trim two opposite edges, but you can trim all four edges if you like.',
      'Spread a thin layer of butter or mayo on one slice of bread, and another thin layer of dijon mustard on the other.',
      'Place one soft boiled egg half in the middle of a bread slice, with the yolk side down.',
      'Spread a layer of egg salad filling around the egg half (up to the height of the soft boiled egg half).',
      'Place the other slice of bread on top.',
      'Slice the sandwich in half, making sure to slice through the egg half as well. Serve immediately.',

    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm7',
    categories: [
      'c1',
    ],
    title: 'Potato Farls',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m7.jpg',
    duration: 25,
    ingredients: [
      '3 medium potatoes, quartered',
      '100g (3 1/2oz) plain flour, plus extra for dusting',
      '1/2 tea spoon baking powder',
      'bacon, to serve (optional)',
      'poached eggs, to serve (optional)',
    ],
    steps: [
      'Boil the potatoes in a large pan of salted water for 12–15 minutes until just soft. Then drain well and return to the pan for 1 min to allow the water to evaporate.',
      'Then press through a potato ricer or mash until really smooth. Weigh out 250g (8oz) of the potato and place in a bowl. Stir in the flour, baking powder and season to taste.',
      'Bring together the mixture to form a soft dough, then place on a lightly floured surface and roll out into a circle about 1cm thick and 15–20cm wide. Cut into 4 wedges. Then dust all over with flour.',
      'Heat a large nonstick frying pan over medium heat (no need to add any oil). Cook the farls for 3–5mins on each side until golden brown and just cooked through. Serve with some bacon and poached eggs.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm8',
    categories: [
      'c1',
    ],
    title: 'Bubble and Squeak Potato cakes',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m8.jpg',
    duration: 30,
    ingredients: [
      '750g potatoes, cubed',
      '1 cabbage, shredded',
      '1 large onion, thinly sliced',
      '2 red chillies, seeded and finely chopped (optional)',
      '2 tsp olive oil',
      '300g unsmoked bacon chops',
      '2 tbsp squeezy honey',
      '1 x 420g can reduced-sugar baked beans',
    ],
    steps: [

    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm9',
    categories: [
      'c1',
    ],
    title: 'Bacon & Cheddar Cornmeal Waffles',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m9.jpg',
    duration: 20,
    ingredients: [
      '1 x 1/2 cups (12oz/340g) all-purpose flour',
      '1 x 1/2 cups (12oz/340g) fine cornmeal',
      '2 tablespoons granulated sugar',
      '1 teaspoon baking powder',
      '1 x 1/2 teaspoon baking soda',
      '1 teaspoon salt',
      '2 x 1/2 cups (20floz/600g) whole milk',
      '2 large eggs',
      '5 tablespoons (2 x 1/2 oz/75g) butter,melted',
      '1/2 cup (4oz/115g) sweetcorn (tinned or frozen)',
      '1 cup (8oz/225g) bacon, chopped',
      '1/2 cup (6oz/180g) cheddar cheese',
      '1 cup (8oz/225g) chopped scallions',
    ],
    steps: [
      'Mix together the wet ingredients in a large bowl.',
      'Mix together the dry in a separate bowl',
      'Add dry to wet and mix gently along with the bacon, onions, cheese and sweet corn.',
      'Mix the batter together until just combined, then incorporate the room temperature melted butter taking care not to overmix the batter from this point.'
          'Cook in a waffle iron for roughly 3 minutes. Like I said if you don’t have a waffle machine fry them off just like pancakes and they will still be great',
      'Serve with bacon, scallions and even scramble eggs on top if you wish.',
      'If you have leftover pancakes wrap them up in foil and reheat them in the oven the next day and they will be lovely.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm10',
    categories: [
      'c1',
    ],
    title: 'Authentic Sri Lankan Pol Roti (Coconut Roti)',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m10.jpg',
    duration: 40,
    ingredients: [
      '3 x 1/3 cup AP flour Measured by spoon and level method, into a cup',
      '1 x 2/3 cup shredded desiccated coconut',
      '1 x 3/4 tsp sea salt',
      '1 medium red onion Finely chopped (generous ½ cup)',
      '3 long, green chili Halved lengthwise and sliced finely.',
      '1/2 cup coconut milk',
      '1/2 cup water',
    ],
    steps: [
      'Place the flour, desiccated coconut, salt, onion, and chili in a large bowl. Mix to combine well.',
      'Mix the water and coconut milk in another bowl or jug.',
      'Add the liquid to the flour mixture, a little at a time, while stirring the flour with your fingertips (or with a fork).',
      'After adding about ½ of the liquid, gently stir the mixture. You will have some clumps and dry spots of flour. Drizzle the liquid over the dry parts of the flour, while mixing, to form a dough.',
      'Add 1 or 2 more tbsp of water ONLY if needed. The dough should come together, but still have dry spots on the surface. This is OK.',
      'If you add too much water, sprinkle in a little extra flour and lightly knead it into the dough (don’t over-knead!). Shape the dough into a rough ball.',
      'Cover the dough (or the bowl) with plastic wrap and let the dough rest for at least 4 hours, or up to 12 hours (room temperature is fine). If you want to store the dough for up to 24 hours, then refrigerate it.',
      'The dough should become really soft after it has rested. If it’s very sticky, generously flour the dough and the work surface to prevent it from sticking to your counter.',
      'Transfer the dough to your floured work surface. Cut the dough into 8 wedges. Lightly roll up each section into a rough ball. See pictures in the post.',
      'Take each dough ball and sprinkle some flour on top and on the work surface. Flatten it to a disc, and then roll it out to a circle using a rolling pin. The roti should be about 0.4-0.5 cm thick, and about 12-15 cm (5-6 inches) in diameter. Cover the rolled out roti with a cloth napkin or plastic wrap, and repeat rolling out all of the dough portions.',
      'Preheat a cast iron skillet or non-stick skillet over medium or medium high heat.',
      'When the pan is heated, transfer a roti onto the skillet and cook for about 2 - 3 minutes, until the bottom starts to develop brown spots.',
      'Flip the roti over and cook the other side for 2 - 3 minutes, until you get brown spots on that side too.',
      'Place the cooked roti on a wire rack to cool down. Repeat with the rest of the roti.',
      'Eat the roti warm or at room temperature.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  // Lunch List: 4 meals
  Meal(
    id: 'm11',
    categories: [
      'c2'
    ],
    title: 'Salad with Smoked Salmon',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m11.jpg',
    duration: 15,
    ingredients: [
      'Arugula',
      'Lambs Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    steps: [
      'Wash and cut salad and herbs',
      'Dice the salmon',
      'Process mustard, vinegar and olive oil into a dessing',
      'Prepare the salad',
      'Add salmon cubes and dressing'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm12',
    categories: [
      'c2',
    ],
    title: 'Delicious Orange Mousse',
    affordability: Affordability.Affordable,
    complexity: Complexity.Advanced,
    imageUrl:
    'assets/m12.jpg',
    duration: 240,
    ingredients: [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Dissolve gelatine in pot',
      'Add orange juice and sugar',
      'Take pot off the stove',
      'Add 2 tablespoons of yoghurt',
      'Stir gelatin under remaining yoghurt',
      'Cool everything down in the refrigerator',
      'Whip the cream and lift it under die orange mass',
      'Cool down again for at least 4 hours',
      'Serve with orange peel',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm13',
    categories: [
      'c2',
    ],
    title: 'Pancakes',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m13.jpg',
    duration: 20,
    ingredients: [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    steps: [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm14',
    categories: [
      'c2',
    ],
    title: 'Creamy Indian Chicken Curry',
    affordability: Affordability.Pricey,
    complexity: Complexity.Intermediate,
    imageUrl:
    'assets/m14.jpg',
    duration: 35,
    ingredients: [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    steps: [
      'Slice and fry the chicken breast',
      'Process onion, garlic and ginger into paste and sauté everything',
      'Add spices and stir fry',
      'Add chicken breast + 250ml of water and cook everything for 10 minutes',
      'Add coconut milk',
      'Serve with rice'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),

  Meal(
    id: 'm15',
    categories: [
      'c2',
    ],
    title: 'Sri Lankan Cauliflower Curry',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m15.jpg',
    duration: 60,
    ingredients: [
      '1 lb cauliflower florets + stem 455 g. Whole cauliflower, just over 1 lb / 455 g',
      '1 tbsp coconut oil or vegetable oil',
      '1 tbsp mustard seeds brown',
      '1/2 medium onion',
      '2 cloves garlic finely chopped or sliced',
      '1/2 inch ginger finely chopped or sliced',
      '1/2 tsp turmeric',
      '1 tsp ground coriander',
      '1 large green chili or 3 small green chili add more or less, depending on your level of spice tolerance and the chili that you have available',
      '1 pandan leaf about 4 – 6 inches',
      '6 – 8 curry leaves',
      '1 1/2 cups coconut milk about 1 can',
      '1/2 tsp sea salt',
      'Salt to taste',
    ],
    steps: [
      'Cut the cauliflower into florets. Slice the remaining cauliflower stalk into 1 – 2 inch length pieces. Wash and set aside.',
      '1 lb cauliflower florets + stem',
      'If your cauliflower head has leaves (that are free of blemishes), you can cut these leaves into larger pieces and wash and set aside these too.',
      'Finely chop or slice the onions. Set aside.',
      '1/2 medium onion',
      'Thinly chop or slice the garlic and ginger as well.',
      '2 cloves garlic,½ inch ginger',
      'In a medium pot that is dry, place the oil, and heat over medium or medium high heat. Make sure the heat does not burn the food at any point.',
      '1 tbsp coconut oil or vegetable oil',
      'When the oil is hot, add the mustard seeds. Saute for a bit to coat the seeds with oil and to prevent them from burning.',
      '1 tbsp mustard seeds',
      'When the mustard seeds start to pop, add the onions, garlic, ginger, curry leaves, pandan leaves, and green chili, and saute until the onions soften.',
      '1/2 medium onion,½ inch ginger,1 large green chili or 3 small green chili,1 pandan leaf,6 – 8 curry leaves,2 cloves garlic',
      'Add the spices, and saute for a few seconds.',
      '1/2 tsp turmeric,1 tsp ground coriander',
      'Add the cauliflower, stems, and salt, and mix well with the rest of the spices. Saute the cauliflower for about 10 minutes until it starts to soften. Lower the heat if needed, to make sure the cauliflower doesn’t burn. (1 lb cauliflower florets + stem,½ tsp sea salt)',
      'Add the cauliflower greens (if using), along with the coconut milk. Stir to mix. If needed, you can increase the heat at this point (if you previously reduced the heat).',
      '1 1/2 cups coconut milk',
      'Bring the coconut milk to a boil, and then immediately lower the heat to a simmer. Let the cauliflower simmer for 10 – 15 minutes until the cauliflower has completely softened. Occasionally stir to prevent the cauliflower from catching at the bottom of the pan and burning.',
      'Keep the lid ajar, if you don’t want the liquid to evaporate too much. OR simmer without the lid, if you want the gravy to thicken as it evaporates. You can also add a little more water as needed to get the desired consistency for your cauliflower curry.',
      'Taste and season the curry to your liking, towards the end of the cook time.',
      'Salt to taste',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm16',
    categories: [
      'c2',
    ],
    title: 'Lemongrass Chicken Bowls',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m16.jpg',
    duration: 15,
    ingredients: [
      '4 tbsp fish sauce 60 mL',
      '4 lemongrass stalks white part, or 4 tbsp lemongrass paste',
      '4 garlic cloves minced, or ½ tsp garlic powder',
      '3 tbsp honey 45 mL',
      '1 tsp freshly ground black pepper',
      '2 tbsp soy sauce 30 mL',
      '1/4 tea spoon cayenne pepper optional',
      '1 kg boneless chicken thighs about 8 – 9 thighs, skinless or skin on',
    ],
    steps: [
      'If you are using lemongrass stalks, finely slice the white part of the lemongrass stalk and then finely mince it. The minced lemongrass will be used in the marinade.',
      'Mix the ingredients for the marinade in a small bowl. Whisk until everything is mixed through. If you prefer, you can add about 1 – 2 tbsp of water to adjust the consistency of the marinade to your liking.',
      'Place the chicken in a ziploc bag, or a large bowl or container. Pour the marinade in and toss the chicken pieces well to make sure all the chicken is well coated in the marinade.',
      'Let the chicken marinate for at least 30 minutes, OR for best results marinate in the fridge overnight (or up to 24 hours).',
      'When ready to cook, heat a non-stick skillet with a drizzle of vegetable oil, over medium heat. You can use a cast iron skillet as well, but you may need to reduce the heat slightly because the cast iron skillet retains more heat.',
      'OPTIONAL – When the pan is heated, pat dry the excess marinade from the chicken pieces using paper towels. This is an optional step, but helps the chicken grill and caramelize better.',
      'Place the chicken thighs on the heated pan, skin side down. Do not overcrowd the pan, so cook in batches.',
      'Cook the chicken for about 5 minutes per side, until the chicken is caramelized on both sides and is cooked through. Adjust the cook times depending on how fast the chicken is caramelizing, since the cook times will vary depending on the size of the chicken and your stove.',
      'Place the cooked chicken on a plate and let it rest for a few minutes.',
      'Slice the cooked chicken thighs, and serve with rice or noodles or a salad, with nuoc cham sauce.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm17',
    categories: [
      'c2',
    ],
    title: 'Homemade Chicken Ramen',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m17.jpg',
    duration: 45,
    ingredients: [
      '2 tbsp mirin',
      '1 tbsp dark soy sauce (Or mushroom dark soy sauce) double the amount of light soy sauce (below) if you don’t have dark soy sauce',
      '1 tbsp light soy sauce',
      '1/4 tsp cayenne pepper',
      '2 garlic cloves chopped finely',
      '4 pieces chicken thigh boneless, skin off or on',
      '2 tsp brown sugar',
      '2 tbsp dark soy sauce (or mushroom dark soy sauce) or 1 tbsp light soy sauce + 1 tbsp water',
      '4 – 5 cups good quality chicken stock preferably no sodium or low sodium',
      '4 stalks of spring onions trimmed and cut in half',
      '4 – 5 cloves garlic',
      '2 inch piece of ginger sliced',
      '4 red chili or 1 tbsp dried chili flakes (crushed red pepper) omit',
      '1/4 cup light soy sauce',
      '1/4 cup mirin',
      '8 ounces shiitake mushrooms stems trimmed and sliced, or cut in half',
      '12 – 13 oz dried ramen noodles or 4 portions (or 4 portions of fresh ramen noodles)',
      '2 bunches of spinach or 4 shanghai bok choy or any Asian greens',
      'Soy sauce',
      'Sesame oil',
      'Garlic',
    ],
    steps: [
      'Place all the ingredients for the chicken marinade in a bowl. Mix well to coat the chicken. If time permits, allow the chicken to marinate for at least 1 hour.',
      'Preheat oven to 425°F, and place an oven rack in the top third of your oven. Line a baking sheet with parchment paper.',
      'Place the chicken pieces on the baking sheet, skin side down (or smooth side down), evenly spaced apart. Then place the baking sheet in the preheated oven (upper third).',
      'Let the chicken roast for 15 minutes. While the chicken is cooking, mix the brown sugar and dark soy sauce for the glaze, and start making the ramen.',
      'After 15 minutes, flip the chicken pieces over and spoon the glaze over them. Let the chicken cook for a further 10 – 15 minutes. Then remove from the oven and let them cool down.',
      'Slice the chicken and set aside.',
      'In one saucepan (Pot 1), place the stock, ginger, garlic, spring onions, chili (if using), soy sauce and mirin. Stir and cover the pot. Let it come to a boil at medium high – high heat. Then lower the heat to medium and let it simmer for 25 minutes. Taste the base and add more soy sauce if needed.',
      'While Pot 1 is simmering, add water to the second pot (Pot 2), and bring it to a boil. Add the dried noodles to the boiling water, and cook according to package directions. I prefer cooking the noodles for ONE MINUTE LESS than what’s recommended on the package, as the noodles will continue to cook for a bit longer when served with hot broth. The straight ramen noodles I use here take 3 minutes to cook. Drain the noodles and divide into 4 bowls and set aside.',
      'When the ramen base in Pot 1 has cooked for about 20 – 25 minutes, strain to remove the garlic, ginger, chili and spring onions (or only the spring onions and chili). Add the strained stock back into the pot and add the mushrooms, and let it cook for a further 5 minutes until the mushrooms have softened. The ramen base is now ready.',

    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm18',
    categories: [
      'c2',
    ],
    title: 'Turkey Sandwich',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m18.jpg',
    duration: 15,
    ingredients: [
      '3 - 4 servings of leftover roast turkey sliced (about 3- 4 slices per person)',
      '2 tbsp unsalted butter',
      '1 - 2 cloves garlic minced',
      'Pinch of salt',
      '4 brioche buns or 8 slices of thick bread (of your choice)',
      'Unsalted butter',
      'Leftover cranberry sauce',
      'Leftover turkey gravy',
      'Shredded lettuce',
      '4 fried eggs',
    ],
    steps: [
      'Preheat oven to 300°F.',
      'Place the sliced roast turkey on a piece of foil, and add the butter, garlic and a pinch of salt on top. Wrap the turkey with the foil.',
      'Place the foil parcel on a quarter sheet pan and transfer to the preheated oven, to reheat the turkey. This will take about 15 minutes, depending on the thickness of your turkey slices. Check after 15 minutes, and return to the oven if the meat needs to be reheated for longer.',
      'Remove from the oven, and increase the oven temperature to 350°F to toast the buns/bread.',
      'Split the brioche buns and spread a thin layer of butter. Place the buns (cut side up), on a sheet pan and transfer to the preheated oven. Toast the buns until the edges are toasty, but still soft in the middle. Remove the buns from the oven.',
      'You can serve all the ingredients separately, so that each person can assemble their sandwiches themselves.',
      'Spread cranberry sauce on the top bun.',
      'Place turkey slices on the bottom bun (3 - 4 slices per person), and top with shredded lettuce.',
      'Pour gravy on top, followed by an egg and the top bun (with cranberry sauce). Enjoy!',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm19',
    categories: [
      'c2',
    ],
    title: 'Beef and Black Bean Chow Mein',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m19.jpg',
    duration: 30,
    ingredients: [
      '40ml groundnut oil',
      '300g beef rump steak, cut into thin strips',
      '1 tsp cornflour',
      '2 tbsp light soy sauce',
      '1 tsp caster sugar',
      '250g egg noodles',
      '3 spring onions, sliced',
      '1 onion, chopped',
      '100g Tesco black stir fry sauce',
      'a few drops of sesame oil, to drizzle',
    ],
    steps: [
      'Whisk together the soy sauce, cornflour and sugar in a small mixing bowl until smooth.',
      'Place the beef in a large mixing bowl and coat with the marinade, mixing well with your hands to coat evenly. As the meat is marinating blanch the egg noodles in a large saucepan of boiling, salted water for 3-4 mins until softened. Drain and refresh in cold water, setting to one side until later.',
      'Heat the groundnut oil in a large wok over a moderate heat until hot. Stir-fry the onion and spring onion, then add the marinated beef. Cook for 2-3 mins, stirring all the time. Drain the the noodles really well, then add to the wok and stir-fry for a further 1-2 mins with the black stir fry sauce until they have been warmed through.',
      'Divide the chow mein between 4 serving bowls, then drizzle a little sesame oil over each. Serve immediately.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm20',
    categories: [
      'c2',
    ],
    title: 'Brazilian-style Beef with RRce',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m20.jpg',
    duration: 25,
    ingredients: [
      '1 tbsp olive or vegetable oil',
      '250g lean beef mince',
      '2 onions, diced',
      '6 spicy chorizo slices, diced',
      '2 garlic cloves, crushed or finely grated',
      '400g tin tomatoes',
      '250g long grain rice',
      '220g green beans, trimmed and roughly chopped into shorter lengths',
      '400g tin kidney beans in chilli sauce',
      '50g extra-mature cheddar, finely grated',
      '150g Greek-style natural yogurt, optional',
      '10g fresh coriander, leaves picked',
    ],
    steps: [
      'Heat the oil in a large, deep frying pan on a medium heat. Fry the beef, onions and chorizo for 5 mins, breaking up the mince with a wooden spoon, until the mince has browned and the onion is translucent.',
      'Stir in the garlic, tomatoes, rice and green beans. Use the tomato tin to add 2 tins of water. Bring to a simmer and cook for 10-12 mins, stirring occasionally, until the rice is just tender. Stir in the chilli beans and heat through for 2-3 mins.',
      'Season to taste, then spoon onto plates. Serve with bowls of grated cheese, coriander leaves and yogurt to serve.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),


  // Dinner List: 10 meals
  Meal(

    id: 'm21',
    categories: [
      'c3',
    ],
    title: 'Turkey Meatballs and Tomato Spaghetti',
    affordability: Affordability.Affordable,
    complexity: Complexity.Advanced,
    imageUrl:
    'assets/m21.jpg',
    duration: 35,
    ingredients: [
      '1/2 500g pack turkey breast mince, 2% fat',
      '1 tsp vegetable oil',
      '1 red onion, thinly sliced',
      '1/4 red pepper, finely chopped',
      '2 garlic cloves, finely crushed',
      '400g tin Grower’s Harvest chopped tomatoes',
      '120g Hearty Food Co. spaghetti',
      '30g Creamfields mature white cheddar, grated',
      '1/4 iceberg lettuce, finely shredded',
      '1/4 cucumber, roughly chopped',
      '3 Nightingale Farms cherry tomatoes, halved',
    ],
    steps: [
      'Roll the turkey mince into 14 equal meatballs. Heat the oil in a frying pan over a medium heat, add the meatballs and fry for 3-5 mins until coloured on the outside. Add the onion and pepper and fry for 3 mins, then stir through the garlic and tinned tomatoes and bring to the boil. Simmer for 10 mins until the meatballs are cooked through and the sauce has thickened slightly.',
      'Meanwhile, bring a pan of water to the boil and cook the spaghetti for 13-15 mins until cooked through. Drain and add to the meatball pan, then toss together until coated.',
      'Divide the spaghetti and meatballs between 2 plates, grate over the cheese and serve with a side salad made with the lettuce, cucumber and tomatoes.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm22',
    categories: [
      'c3'
    ],
    title: 'Asparagus Salad with Cherry Tomatoes',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m22.jpg',
    duration: 30,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),

  Meal(
    id: 'm23',
    categories: [
      'c3',
    ],
    title: 'Indian Masala Omelette',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m23.jpg',
    duration: 35,
    ingredients: [
      '15ml (1tbsp) sunflower or vegetable oil',
      '1 garlic clove, crushed',
      '2 spring onions',
      '1 medium tomato',
      '1/2 medium green chilli',
      '1 tsp medium curry powder',
      '1/2tsp garam masala',
      '2 eggs',
      '1 tbsp fresh coriander',
    ],
    steps: [
      'Heat 1 tbsp of sunflower or vegetable oil in a 20.5cm (8in) nonstick frying pan',
      'Add 1 clove crushed garlic, 2 spring onions, 1 medium tomato and 1/2 medium green chilli, chopped.',
      'Cook for 2-3 minutes until soft. Add 1 tsp medium curry powder and 1/2 tsp garam masala and fry for a further minute.',
      'Beat 2 eggs together in a small bowl and season.',
      'Add the egg mixture to the pan and swirl the pan until the omelette mixture is cooked underneath.',
      'Carefully flip the omelette over and cook for 1-2 minutes, until golden.',
      'Scatter with 1 tbsp of fresh coriander and serve immediately.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm24',
    categories: [
      'c3',
    ],
    title: 'Slow-cooker Lamb Liver, Bacon and Onions',
    affordability: Affordability.Affordable,
    complexity: Complexity.Advanced,
    imageUrl:
    'assets/m24.jpg',
    duration: 500,
    ingredients: [
      '2 tbsp unsalted butter',
      '4 rashers smoked back bacon, cut into strips',
      '450g pack sliced lamb’s liver',
      '3 tbsp plain flour',
      '1 onion, thinly sliced',
      '1 beef stock cube, made up to 500ml',
      '1 tsp Worcestershire sauce',
      '1 bay leaf',
      'mashed potato and peas, to serve (optional)',
    ],
    steps: [
      'Heat a nonstick frying pan with half the butter over a medium heat and fry the bacon for 3-4 mins until crispy. Remove with a slotted spoon and set aside on kitchen paper.',
      'Pat dry the livers, then toss with 2 tbsp flour and plenty of seasoning. Shake of any excess, then cook in the bacon fat over a medium heat for 1-2 mins each side until browned. Set aside.',
      'Add the remaining butter to the pan with the onion and cook for 8-10 mins over a medium-low heat until lightly golden. Stir in the bacon and liver.',
      'Mix the remaining flour with 2 tbsp stock. Transfer the liver mix to a slow-cooker. Set to low, then pour in the remaining stock, the Worcestershire sauce, bay leaf and the flour paste. Stir well, then cook for 6-8 hrs until the liver is tender and the sauce silky. Serve with mash and peas, if you like.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm25',
    categories: [
      'c3',
    ],
    title: 'Pad Thai Noodles',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m25.jpg',
    duration: 18,
    ingredients: [
      '2 tbsp sunflower oil',
      '200g raw tiger prawns, peeled and de-veined',
      '1 clove garlic, crushed',
      '2.5cm (1in) piece root ginger, peeled and grated',
      '1 egg, beaten',
      '2 x 200g packs Sharwoods Stir Fry Pad Thai noodles',
      '2 medium carrots, grated',
      '300g bean sprouts',
      '1 tbsp brown sugar',
      '3 tbsp fish sauce',
      'zest and juice of 1 lime',
      '50g peanuts, finely chopped',
      '1 red chilli, thinly sliced',
      '3 spring onions, sliced',
      'handful parsley leaves, finely chopped',
    ],
    steps: [
      'Heat the oil in a wok or large frying pan and stir-fry the prawns for 3-4 minutes until just pink. (If you are using ready-cooked prawns, defrost if frozen, and stir-fry for just 1 minute). ',
      'Add the garlic and ginger, cook for 1 minute more, then add the beaten egg and cook, stirring until lightly scrambled.',
      'Add the noodles, carrot, bean sprouts, sugar, fish sauce and lime zest and juice and cook for 1-2 minutes until piping hot.',
      'Sprinkle with the peanuts, chilli, spring onions and fresh parsley. Serve hot or cold.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm26',
    categories: [
      'c3',
    ],
    title: 'Gingered Chicken Noodles',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m26.jpg',
    duration: 20,
    ingredients: [
      '1 tbsp stir-fry or vegetable oil',
      '500g (1lb) chicken breast fillets, sliced',
      '2 carrots cut into thin sticks',
      '1 red pepper, deseeded and sliced',
      '150g (5oz) broccoli florets',
      '250g (8oz) baby corn or sugarsnap peas',
      '2-3 tsp frozen chopped ginger',
      '1 clove garlic, crushed',
      '1 x 400g pack Ready To Wok Thai Ribbon Noodles',
      '100ml (3 1/2fl oz) chicken stock',
      '3 tbsp sweet chilli dipping sauce',
      '3 tbsp chopped fresh coriander',
    ],
    steps: [
      'Heat the oil in a large wok or frying pan.',
      'Add the chicken and stir-fry for 8 minutes.',
      'Add the carrots, peppers and broccoli and stir-fry for 4 mins.',
      'Cut the baby corn in half and add to the wok with the sugarsnap peas, ginger and garlic. Stir-fry for 3 mins. ',
      'Finally, add the noodles, stock, chilli sauce and coriander and mix well. Cut into a portion of the chicken and ensure it is cooked through, with no pink showing. Serve.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm27',
    categories: [
      'c3',
    ],
    title: 'Parmesan crumb chicken with winter slaw',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m27.jpg',
    duration: 30,
    ingredients: [
      '1/2 red cabbage, cored and thinly shredded',
      '1 small red onion, sliced',
      '1 carrot, peeled and sliced',
      'seeds from 1 pomegranate',
      '1 lemon, juiced and zested',
      '2 tbsp extra-virgin olive oil',
      'pinch sugar',
      '4 chicken breasts',
      '3 tbsp parmesan',
      '150g breadcrumbs',
      'handful fresh parsley, chopped',
      '75g (3oz) plain flour',
      '2 eggs, beaten',
      '2 tbsp oil',
      'new potatoes, to serve',
    ],
    steps: [
      'Toss together the slaw ingredients. Put the chicken breasts between pieces of clingfilm and beat with a rolling pin to about 1cm (½in) thick.',
      'Mix together the Parmesan, breadcrumbs and parsley on a plate. ',
      'Season the flour and put on another plate. ',
      'Put the egg on a third plate. ',
      'Dip the chicken first in the flour, then in the egg and then in the breadcrumbs.',
      'Heat the oil in a large frying pan and cook the chicken for about 3-4 minutes on each side. ',
      'Cut into a thick portion to ensure that it is cooked through, with no pink showing.' ,
      'Serve with the slaw and boiled new potatoes, if you like.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm28',
    categories: [
      'c3',
    ],
    title: 'Steak with Cheese and Chive Polenta',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m28.jpg',
    duration: 25,
    ingredients: [
      '300g (10oz) cherry tomatoes on the vine',
      '200g (7oz) asparagus, trimmed',
      '1 tbsp olive oil',
      '1 tsp mixed dried herbs',
      '2 garlic cloves, gently crushed',
      '2 quick-fry beef steaks',
      '500ml (17fl oz) chicken stock',
      '75g (3oz) dry polenta',
      '20g (3/4oz) Parmesan, grated',
      '50g blue cheese, crumbled',
      '1/2 x 30g pack fresh chives, chopped, plus extra to garnish',
    ],
    steps: [
      'Preheat the grill to medium- high. ',
      'Put the tomatoes and asparagus on a baking tray and drizzle over half the olive oil with the dried herbs and the garlic cloves.' ,
      'Gently mix together and grill for 10 minutes.',
      'Meanwhile, heat the remaining oil in a pan over a high heat until searing hot, then fry the steaks for 2-3 minutes each side for medium-rare, or 4-5 minutes each side for well done.' ,
      'Remove and set aside to rest for 5 minutes.',
      'Bring the stock to the boil in a large pan and pour in the polenta. ',
      'Cook over a low heat for 5 minutes, stirring constantly. ',
      'Add in the Parmesan and blue cheese, then add seasoning. Once the cheese has melted, stir through the chives.',
      'Serve the steak with the polenta and grilled vegetables, garnished with the extra chives.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm29',
    categories: [
      'c3',
    ],
    title: 'Korean Bulgogi Beef Baguette',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m29.jpg',
    duration: 20,
    ingredients: [
      '1 x 450g beef sirloin steak, cut into very thin slices',
      '1 large baguette',
      '4 tbsp mayonnaise',
      '2 spring onions, thinly sliced',
      '1 red chilli, seeded and finely chopped',
      '70g (2 1/2oz) rocket',
      '2 tbsp soy sauce',
      '4 tsp honey',
      '4 tsp toasted sesame seed oil',
      '1/4 onion, roughly chopped',
      '2cm piece ginger, peeled',
      '4 garlic cloves',
      '1/2 tsp freshly ground black pepper',
    ],
    steps: [
      'Put all of the marinade ingredients into a food processor and blitz until smooth. ',
      'Pour over the sliced beef, cover and chill in the fridge for at least 15 minutes or overnight.',
      'Meanwhile, cut the baguette into 4 pieces. ',
      'Cut each in half and spread a little mayonnaise on one side of the bread. ',
      'Top with the rocket and set aside.',
      'When ready to serve, heat a large pan over a high heat. ',
      'When very hot, add the beef and fry for 4-5 minutes, until cooked through and slightly charred and caramelised. ',
      'Divide the beef between the sandwiches and sprinkle over the spring onions and red chilli. Serve immediately.',

    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm30',
    categories: [
      'c3',
    ],
    title: 'Mexican Chicken Mole',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m30.jpg',
    duration: 210,
    ingredients: [
      '4 under-ripe tomatoes',
      '2 red chillies, halved',
      '2 green chillies, halved',
      '2 tbsp vegetable oil',
      '1 onion, finely sliced',
      '6 garlic cloves',
      '1 lemon, zest and juice',
      '30g sesame seeds',
      '75g (3oz) ground almonds',
      '1 tsp cinnamon',
      '1 tsp whole peppercorns, grounded',
      '1/2 tsp whole cloves, grounded',
      '1 slice stale bread',
      '40g (1 1/2oz) dark chocolate',
      '600ml (1 pint) chicken stock',
      '1 1/2 tbsp chipotle sauce',
      '4 chicken legs',
      '1 star anise',
      '2 tsp dried oregano',
      '70g (3oz) smooth peanut butter',
      'rice, to serve',
    ],
    steps: [
      'Preheat the oven to gas 7, 220°C, fan 200°C.',
      'On a tray, combine the tomatoes and chilli and bake until soft and starting to char. ',
      'In a large, heavy-based saucepan, add the butter and oil and cook the onion until soft.' ,
      'When it is beginning to go translucent, add in the garlic.',
      'Add the tomatoes, chillies, lemon zest and juice, sesame seeds and ground almonds and cook for 5 minutes.',
      'Using a pestle and mortar, grind the whole peppercorn and cloves. ',
      'Add the cinnamon, peppercorn, cloves, bread, chocolate, stock and chipotle, and cook for a further 5 minutes. ',
      'Then blitz in a food processor until smooth.',
      'Put the chicken in a clean, large saucepan and pour over the sauce. ',
      'Add the star anise, oregano and peanut butter. ',
      'Put a lid on the saucepan and cook on low for 2 hours until the chicken is tender. Serve with rice.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),


// Dessert List: 6 meals
  Meal(
    id: 'm40',
    categories: [
      'c4',
    ],
    title: 'Chocolate Souffle',
    affordability: Affordability.Affordable,
    complexity: Complexity.Advanced,
    imageUrl:
    'assets/m40.jpg',
    duration: 45,
    ingredients: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    steps: [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm41',
    categories: [
      'c4',
    ],
    title: 'Chocolate Cake',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m41.jpg',
    duration: 45,
    ingredients: [
      '220g unsalted butter, softened',
      '220g (7 3/4oz) caster sugar',
      '200g self-raising flour',
      '4 large eggs',
      '1 tsp baking powder',
      '1 tsp vanilla extract',
      '3 tbsp cocoa powder',
      '2 tbsp milk',
      'small pinch salt',
      '300ml (10oz) double cream',
      '300g (10oz) dark chocolate',

    ],
    steps: [
      'Preheat the oven to gas 4, 180°C, fan 160°C.',
      'Grease and line 2 x 20cm (8in) cake tins and set aside.' ,
      'In a large bowl, beat together the butter and sugar until pale.' ,
      'Add all the remaining sponge ingredients and beat together until well combined.' ,
      'Divide the mixture between the cake tins and smooth the tops. ',
      'Bake in the oven for 20-25 minutes or until an inserted skewer comes out clean. ',
      'Once baked, cool in the tins for 10 minutes, then remove from the tins and transfer to a cooling rack to cool completely.',
      'Accept all cookies',
      'Meanwhile, make the ganache. Heat the double cream gently in a saucepan and break up the dark chocolate into cubes and place in a bowl. ',
      'When the cream is just under the boil, pour it over the dark chocolate, ensuring it’s all covered, and allow to stand for 2-3 minutes. ',
      'Whisk the ganache gently until it starts to combine and goes glossy. ',
      'Allow to cool for 10 minutes, then place in the fridge for around 30 minutes, until it is a spreadable consistency.',
      'Once the sponges are cool, lay one with the topside down on a cake stand and spread with 1/3 of the ganache mixture. ',
      'Top with the other sponge, topside up and push down slightly to secure it onto the filling. ',
      'Ice the top of the cake with the remaining mixture by piling it in the centre and spreading it to the sides of the top sponge. ',
      'Bring it down the sides gradually and smooth with a palette knife. Serve in large slices.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm42',
    categories: [
      'c4',
    ],
    title: 'Victoria Sponge Cake',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m42.jpg',
    duration: 45,
    ingredients: [
      '160g unsalted butter, softened',
      '160g self-raising flour, sifted',
      '160g caster sugar',
      '3 large eggs, lightly beaten',
      '1 tsp vanilla extract',
      '100ml double cream',
      '125g strawberry jam',
      '1 tbsp icing sugar, for dusting',
    ],
    steps: [
      'Pre-heat the oven to gas 3, 170°C, fan 150°C. Grease and line 2 x 8 inch (20cm) springform cake tins with nonstick baking paper.',
      'In a large mixing bowl, cream together the butter, vanilla extract and sugar using an electric hand held whisk until light and fluffy.',
      'Add the lightly beaten egg a tablespoon at a time, beating well between additions, until fully incorporated. ',
      'Carefully fold the flour in using a large metal spoon and spoon the batter evenly into the two prepared cake tins.',
      'Bake for 25-30 minutes until springy to the touch and a cake tester comes out clean when inserted into the centre of the cakes.',
      'Remove and allow the tins to cool on a wire rack for 5 minutes before turning out and peeling away the nonstick baking paper.',
      'Whip the cream to soft peaks as the cakes cool, then spread the bottom half of the cake with the cream in an even layer.',
      'Spread the strawberry jam evenly and carefully on top of the cream. ',
      'Sandwich the cake with the other half of the cake and transfer it carefully to a serving plate. ',
      'Dust with the icing sugar and serve.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm43',
    categories: [
      'c4',
    ],
    title: 'White Chocolate Cheesecake',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m43.jpg',
    duration: 220,
    ingredients: [
      '120g digestive biscuits, pulsed into fine crumbs',
      '70g unsalted butter, melted',
      '2 sheets gelatine',
      '2 tbsp lemon juice',
      '350g low-fat cream cheese',
      '100g caster sugar',
      '200g low-fat Greek yogurt',
      '150g white chocolate, chopped',
      '1 tbsp vanilla extract',
      '150g white chocolate, chopped',
      'sugar rose, to garnish (optional)',
    ],
    steps: [
      'Combine the fine biscuit crumbs with the melted butter until you have the consistency of wet sand. ',
      'Line a 20cm straight-sided springform tart tin with nonstick baking paper. ',
      'Use the biscuit mixture to line the base of the tin, then transfer to the fridge to set.',
      'Meanwhile, soften the gelatine in the lemon juice and a little water if necessary, for 5 mins. ',
      'Heat the mixture in a small saucepan over a low heat until the gelatine has dissolved. ',
      'Place the chopped white chocolate in a heatproof bowl and sit over a saucepan of gently simmering water, stirring occasionally until smooth. ',
      'Remove to one side to cool a little.',
      'Beat together the low-fat cream cheese and the sugar in a large mixing bowl using an electric hand-held whisk for 2 mins. ',
      'Add the low-fat Greek yogurt and gelatin mixture, and mix again until smooth. ',
      'Then fold in the cooled, melted white chocolate. ',
      'Finally, add the vanilla extract and beat well.',
      'Pour onto the biscuit base and tap gently on the side to release any trapped air bubbles. ',
      'Transfer to the fridge and chill for 2-3 hours until set.',
      ' When ready to serve, remove from the tin and remove the nonstick baking paper and cheesecake as one. ',
      'Garnish the centre of the top of the cheesecake with the grated chocolate and sit the sugar rose on top if using. ',
      'Cut into portions using a hot, sharp knife.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm44',
    categories: [
      'c4',
    ],
    title: 'Gluten-free Chocolate Fudge Brownies',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m44.jpg',
    duration: 210,
    ingredients: [
      '225g plain gluten-free chocolate',
      '140g butter',
      '4 large eggs',
      '225g golden caster sugar',
      '100g Doves Farm Gluten Free white self-raising flour',
      '1 tbsp cocoa powder',
    ],
    steps: [
      'Preheat the oven to Gas Mark 4, 180℃, fan 160℃. ',
      'Line a rectangular tin (27cm x 17.5cm x 3.5cm) with nonstick baking paper. ',
      'Break 175g of the chocolate into pieces and put into a glass bowl over a pan of simmering water along with the butter. ',
      'When melted, take the bowl off the pan and put aside.',
      'Chop the rest of the chocolate into small chunks and set aside.',
      'Whisk the eggs and sugar together in a large bowl using an electric hand mixer, until thick, pale, fluffy and almost doubled in volume.',
      'Pour in the cooled melted chocolate, and gently fold, before sifting in the flour and cocoa and gently folding again. ',
      'Lastly stir in the chopped chocolate.',
      'Pour the mixture into the lined tin and lightly spread it into all the corners. ',
      'Bake for about 20 mins, or until the middle is just set and the top is crusty. ',
      'Remove from the oven and leave to cool in the tray. ',
      'Finish off by sprinkling over some cocoa powder.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm45',
    categories: [
      'c4',
    ],
    title: 'Double Chocolate Tiramisu',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m45.jpg',
    duration: 210,
    ingredients: [
      '400ml coffee',
      '50g caster sugar',
      '75ml marsala wine',
      '200g pack sponge fingers',
      '100g white chocolate, chopped',
      '4 egg yolks',
      '125g caster sugar',
      '50ml marsala wine',
      '250g mascarpone',
      '200g light soft cheese',
      '125g half fat créme fraîche',
      '1 tsp cocoa powder',
      '25g dark chocolate',
    ],
    steps: [
      'Put the coffee and 50g caster sugar in a medium saucepan and boil down for around 10 mins to reduce the volume by half.',
      'Add the 75ml marsala and pour into a shallow dish. ',
      'Briefly soak half of the sponge fingers in the coffee mixture - they need only a few seconds or they fall apart. ',
      'Lay them across the base of a large, 24cm diameter serving bowl or dish.',
      'For the mascarpone mix, melt the white chocolate in a bowl set over a saucepan of gently simmering water (or melt in the microwave) until just melted, then remove the bowl from the pan and set aside to cool slightly. ',
      'Put the egg yolks, caster sugar and marsala in a large heatproof bowl.',
      'Place over a saucepan filled with 2.5cm simmering water.',
      'Using an electric hand whisk, beat the mixture over the simmering water for 7-8 mins until thick and paler in colour. ',
      'Remove from the heat and continue to whisk for several minutes until thicker and cooled - and when the beaters are lifted the mixture leaves a ribbon trail. Set aside.',
      'In a separate large bowl, beat the mascarpone and soft cheese with a wooden spoon until smooth. ',
      'Stir in the crème fraîche. Using a spatula, fold the mascarpone mix into the egg yolk mixture, then fold in the cooled white chocolate. ',
      'Spoon or pour half of this mixture over the sponge finger layer.',
      'Briefly soak the remaining sponge fingers in the coffee mixture as before and lay them on top of the mascarpone mixture, cutting to fit if necessary. ',
      'Pour over the remaining mascarpone mixture, to evenly cover the fingers.',
      'Sift the cocoa powder over the surface then grate over the dark chocolate. ',
      'Cover with cling film and chill for at least 3 hrs, or up to 24 hrs, to firm up before serving.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  // Vegetarian List: 10 meals

  Meal(
    id: 'm50',
    categories: [
      'c5',
    ],
    title: 'Red lentil dosa pancakes with potato and spinach',
    affordability: Affordability.Affordable,
    complexity: Complexity.Intermediate,
    imageUrl:
    'assets/m50.jpg',
    duration: 210,
    ingredients: [
      '175g red lentils, soaked overnight in 500ml water',
      '600g baby potatoes, cut into 1-2cm chunks',
      '250g Plant Chef coconut korma sauce',
      '200g baby spinach',
      '1-2 tsp vegetable oil',
      '125g Greek-style natural yogurt',
      '1/2 small garlic clove, crushed',
      '1/4 red onion, diced',
      '100g red cabbage, grated',
      '2 carrots, peeled and grated',
      '1/2 lemon, juiced',
    ],
    steps: [
      'Put the red lentils in a bowl with 500ml water. ',
      'Cover and set aside to soak for at least 6 hrs, or overnight.',
      'When ready to cook, boil the potatoes for 8-10 mins until tender; drain. ',
      'Whisk the yogurt with the garlic, some seasoning and 2-3 tsp water to make a sauce thin enough to drizzle. ',
      'Mix together the kachumber ingredients with a little seasoning.',
      'To make the pancakes, drain the lentils and rinse briefly. ',
      'Transfer to a blender with 300ml water and 1 tsp fine salt. Blend until smooth.',
      'Heat a nonstick frying pan over a medium-high heat and brush with a little oil. ',
      'Pour in 1⁄8 of the batter and spread to a pancake 16cm wide. ',
      'Cook for 2 mins or until the top looks dry and the underside is pale golden. ',
      'Flip, cook for 1 min, then transfer to a plate. Repeat to make 7 more.',
      'Add the potatoes and curry sauce to the frying pan with 100ml water. ',
      'Cook for 4 mins until beginning to thicken. Fold through the spinach and cook for 2 mins. ',
      'Pile the potato curry and salad into the pancakes, drizzling with garlic yogurt to serve.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm51',
    categories: [
      'c5',
    ],
    title: 'Celeriac, Garlic and Thyme Dauphinoise',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m51.jpg',
    duration: 105,
    ingredients: [
      '875g celeriac',
      '150ml half-fat crème fraîche',
      '250ml skimmed milk',
      '2 garlic cloves, crushed',
      '1 tbsp fresh thyme leaves',
      '50g Parmesan or Cheddar cheese',
    ],
    steps: [
      'Preheat the oven to gas 3, 170°C, fan 150°C.',
      'Peel, quarter and thinly slice the celeriac.',
      'Bring the crème fraîche and milk to the boil and add the celeriac and crushed garlic. ',
      'Simmer gently for 3-4 minutes, stirring every so often so the celeriac does not stick to the pan.',
      'Spoon into an ovenproof dish. ',
      'Press the celeriac down as you go and scatter the thyme in between layers. ',
      'Top with the cheese and bake for about an hour and a half until golden and bubbling. ',
      'Serve with roast beef, chicken or steak.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm52',
    categories: [
      'c5',
    ],
    title: 'Carrot and Egg Omelette',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m52.jpg',
    duration: 15,
    ingredients: [
      '4 eggs'
          'white pepper, to taste',
      '2 spring onions, finely sliced, separated into greens and whites',
      '1 tbsp vegetable oil',
      'small piece of ginger, sliced into matchsticks',
      '1 large carrot (or 2 small carrots), peeled and julienned',
      'rice, to serve',
      'sesame seeds, to serve (optional)',
      'sriracha sauce or chilli oil, to serve (optional)',
    ],
    steps: [
      'Beat the eggs in a bowl. ',
      'Add a pinch of salt and white pepper, and half the green spring onions; whisk well.',
      'Heat the oil in a small 24cm frying pan, add half the white spring onions and half the ginger. ',
      'Sauté for 1 min until aromatic.',
      'Add half the carrots. ',
      'Stir-fry for 4-5 mins on a high heat until the carrots are cooked and softened. ',
      'Add more oil if needed.',
      'Spread out the veg, then add half the beaten eggs. ',
      'Cook for another 1-2 mins, then carefully flip the omelette. ',
      'Remove from the pan. ',
      'Repeat to make a second omelette with the rest of the eggs, carrots, ginger and white spring onions.',
      'Serve the omelettes on top of rice and garnish with the remaining green spring onions. ',
      'Top with a sprinkle of sesame seeds and a drizzle of chilli oil, sriracha or any sauce of your choice.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm53',
    categories: [
      'c5',
    ],
    title: 'Winter Vegetable Laksa',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m53.jpg',
    duration: 40,
    ingredients: [
      '2 shallots, roughly chopped',
      '2 garlic cloves, roughly chopped',
      '2 stalks lemongrass, finely sliced',
      '2 red chillies, deseeded and roughly chopped',
      '5cm fresh ginger, peeled and finely chopped',
      '1 tsp ground turmeric',
      '4 kaffir lime leaves, roughly chopped',
      'For the curry',
      '85g swede, cut into 1cm (1/2 in) cubes',
      '85g sweet potato, cut into 1cm (1/2 in) cubes',
      '85g carrot, cut into 1cm (1/2 in) cubes',
      '4 tbsp vegetable oil for frying',
      '1 x 396g pack tofu, quartered',
      '1 x 400ml tin coconut milk',
      '200ml vegetable stock',
      '4 tbsp light soy sauce',
      '2 tsp sugar, preferably palm if available',
      '100g (3 1/2 oz) green beans cut into 2cm (1in) strips',
      '150g (5oz) rice noodles',
      '12 cherry tomatoes, halved',
      '1 small bunch coriander, leaves picked',
      '1/2 bunch mint, leaves picked',
      '2 spring onions, thinly sliced',
      '2 limes, halved',
    ],
    steps: [
      'To make the laksa paste, whizz all the ingredients and 4 tbsp of water in a blender until smooth.',
      'To make the curry, put the sweet potato, swede and carrot cubes in a saucepan. ',
      'Cover them with water and cook until tender. ',
      'Drain, reserving 600ml (1pt) of the cooking liquid.',
      'Heat 2 tbsp of oil in a wok, add the tofu and fry until crisp. ',
      'Remove and lay on absorbent paper. ',
      'Add a further 2 tbsp of oil to the wok and heat, spoon in the laksa paste and fry for 2 minutes to release the aromas. ',
      'Add the coconut milk, stock, soy sauce, sugar and reserved cooking liquid.',
      'Bring to the boil, then simmer for 7 minutes. ',
      'Add the green beans and cook for a further 3 minutes, until the beans are tender.',
      'Meanwhile, put the noodles in a large heat-proof bowl, cover with boiling water and set aside for 10 minutes.',
      'Drain and divide among 4 deep warmed bowls. ',
      'Top with the tomatoes, vegetables and tofu. ',
      'Ladle over the soup, garnish with the herbs and spring onions and serve with a wedge of lime.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm54',
    categories: [
      'c5',
    ],
    title: 'Malpua',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m54.jpg',
    duration: 60,
    ingredients: [
      '150g plain flour',
      '3 cardamon pods, seeds removed and crushed',
      '1 tsp fennel seeds',
      '350ml semi-skimmed milk',
      'Sliced mango tossed with a squeeze of lime juice, to serve',
      'Roughly chopped pistachios, to serve',
      'Flaked almonds, to serve',
      '200g caster sugar',
      'Large pinch of saffron strands',
    ],
    steps: [
      'Make a batter.',
      'Put the flour, cardamon and fennel in a measuring jug with a pinch of salt. ',
      'Gradually whisk the milk into the mixture until you have a smooth batter. ',
      'Leave the rest while you make the sugar syrup.' ,
      'Put the sugar in a small, heavy-based saucepan with 100ml water and place over a medium heat. ',
      'Allow the sugar to melt completely, then bring to a rolling boil and cook for around 1 min, until the mixture is lightly syrupy.',
      'Remove the syrup from the heat, scoop a little out with a teaspoon, cool for a few secs, then dip your forefinger in it and press together with your thumb. ',
      'Bring them apart and back together quickly a few times - if your syrup is the right consistency, it should form short threads between your finger and thumb that break when they get to around 1cm long. If they do not, boil it for a bit longer - if they hold for more than 1cm, stir in a little hot water and try again. The consistency is important to the finished texture of the malpua.',
      'Transfer the sugar syrup to a wide-based bowl, stir in the saffron and leave to cool completely. ',
      'Once they batter has rested and the syrup is cool, heat a large, wide, heavy-bottomed saucepan with around 2cm sunflower oil or ghee in it. ',
      'Bring it to 180°C when tested with a digital kitchen thermometer, then try and keep it around this temperature. ',
      'Give the batter a stir, then pour in enough to form a pancake around 8-10cm wide. ',
      'The batter should sizzle around the edges, giving them a frill. ',
      'Cook for around 1 min until the underside is deep golden, then flip and repeat.',
      'Remove the pancake from the oil with a slotted spoon and drain briefly on kitchen paper, before dipping into the bowl of syrup sugar. ',
      'Let it soak in for around 20 secs, then turn and repeat, before lifting it out carefully and allowing the excess syrup to drop off. ',
      'Transfer to a plate and repeat the process with the remaining malpua. ',
      'Serve topped with sliced mango, scattered with pistachios and flaked almonds, while still warm. ',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm55',
    categories: [
      'c5',
    ],
    title: 'Dhal Soup',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m55.jpg',
    duration: 70,
    ingredients: [
      'olive oil',
      '1 tsp black mustard seeds',
      '1 white onion, finely chopped',
      '1/2 tsp garlic paste',
      '1/2 tsp ginger paste',
      '2 red chillies, finely chopped',
      '1 tsp baharat',
      '1/2 tsp ground turmeric',
      '1 tomato, diced',
      '200g red lentils',
      '400ml tin coconut milk',
      '1 tsp salt',
      'Juice of 1 lemon',
      'Crispy fried onions, to serve (optional)',
    ],
    steps: [
      'Coat the base of a medium-large pan with a thin layer of oil, add the mustard seeds and fry over a medium-high heat for 2 mins until they start to pop.',
      'Add in the onion, garlic, chillies, baharat and turmeric, and sauté until the onions begin to turn light brown. ',
      'Add in the tomatoes and sauté until they soften.',
      'Add in the lentils, coconut milk, 1 ltr water and the salt, and simmer over a medium heat for 30 mins until thickened and the lentils are cooked.',
      'Add in the lemon juice and simmer for a further 5 mins.',
      'To serve, either purée the soup or leave it as it is for more texture. ',
      'You can also serve with crispy fried onions on top, if you like.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm56',
    categories: [
      'c5',
    ],
    title: 'Jamie Veggie Caesar Salad',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m56.jpg',
    duration: 20,
    ingredients: [
      '1 x 400g tin of chickpeas',
      '150g leftover bread',
      '1 clove of garlic',
      '2 tbsp olive oil',
      '160g frozen green beans',
      '6 tbsp natural yogurt',
      '2 tsp mustard, such as Dijon, English, wholegrain',
      '2 tbsp red wine vinegar',
      '20g Parmesan cheese (or veggie hard cheese alternative)',
      '1 romaine lettuce',

    ],
    steps: [
      'Boil the kettle. ',
      'Preheat the oven to gas 6, 200°C, fan 180°C. ',
      'Drain the chickpeas, tip into a heatproof bowl and cover with boiling water for 5 mins.',
      'Tear the bread into chunks and pop in a roasting tray with the unpeeled garlic. ',
      'Drain and add the chickpeas, drizzle over 2 tbsp of olive oil, then toss it all together and roast for 12 mins until the bread is golden and the chickpeas are crispy. ',
      'Preheat a griddle or large frying pan over a high heat, add the frozen beans and cook for 4 mins, or until softened and charred.',
      'Remove the croutons and chickpeas from the oven, carefully take out the garlic and set aside. ',
      'Once cool enough to handle, squeeze the softened garlic out of its skin into a bowl. ',
      'Stir in the yogurt, mustard and 2 tbsp of red wine vinegar, then grate in most of the Parmesan and season to perfection, tweaking the mustard and vinegar to your taste.',
      'To serve, spread the dressing over a serving dish. ',
      'Click off the lettuce leaves and tear over the dressing. ',
      'Scatter over the beans, chickpeas and croutons, and serve with an extra grating of Parmesan, if you like. ',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm57',
    categories: [
      'c5',
    ],
    title: 'Sweet Potato Shoestring Fries',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m57.jpg',
    duration: 45,
    ingredients: [
      '2 large sweet potatoes, peeled',
      '1 tbsp olive oil',
    ],
    steps: [
      'Preheat the oven to gas 2, 150°C, fan 130°C. ',
      'Using a julienne peeler or a spiralizer, cut the sweet potatoes into long, thin curls or strips (if you do not have a julienne peeler or a spiralizer use a knife instead).',
      'Coat in the oil and lay out in a single layer on 2 large baking trays and sprinkle with salt. ',
      'Bake for 40-45 mins or until the fries are crisp and golden. ',
      'Allow to cool and serve.',

    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm58',
    categories: [
      'c5',
    ],
    title: 'Spicy Potato Wedges with Onion, Chive and Sour Cream Dip',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m58.jpg',
    duration: 70,
    ingredients: [
      '1kg (2Ib) medium-sized Désirée potatoes, sliced into wedges (skins on)',
      '60ml (4tbsp) olive oil',
      '2 garlic cloves, crushed',
      '1 tbsp cornflour',
      '1-2 tsp smoked paprika, to taste',
      '1 onion, halved and finely sliced',
      '1⁄2 bunch chives, chopped, plus extra',
      '150g (5oz) sour cream',
    ],
    steps: [
      'Preheat the oven to Gas Mark 6, 200°C, fan 180°C. ',
      'Toss the wedges with 3 tbsp of the oil and the garlic, season, and spread out in a roasting tin. ',
      'Cover with foil and cook for 25 minutes.',
      'Remove the foil and sprinkle the potatoes with the cornflour and paprika. ',
      'Roast for a further 35-40 minutes until browned and crisp at the edges, turning halfway through.',
      'Meanwhile, make the dip. ',
      'Gently fry the onion in the remaining oil for 10 minutes until very soft. ',
      'Increase the heat and cook, stirring, for another 5 minutes, until golden and crisp in places. ',
      'Cool. ',
      'Stir most of the chives, half the onion and a little seasoning into the sour cream. ',
      'Scatter with the remaining caramelised onion and chives. ',
      'Serve in a dipping bowl with the wedges.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm59',
    categories: [
      'c5',
    ],
    title: 'Healthy Pancakes with lemon Cream Cheese',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m59.jpg',
    duration: 30,
    ingredients: [
      '100g light cream cheese',
      '1 lemon, juiced and finely zested, plus extra to garnish',
      '200g wholemeal plain flour',
      '1 tsp baking powder',
      'small handful basil leaves, chopped',
      'small handful parsley, chopped',
      '2 eggs, separated',
      '200ml semi-skimmed milk',
      'butter, for greasing',
      '1 avocado, quartered and sliced',
      '150g cherry tomatoes, halved',
    ],
    steps: [
      'In a bowl, combine the cream cheese with the lemon zest and juice. ',
      'Season with freshly cracked black pepper and set aside until needed.',
      'Sift the flour, baking powder, herbs and 1/4 tsp salt into a large mixing bowl and make a well in the centre.',
      'Add the egg yolks and half the milk. ',
      'Using a fork, gently stir to combine, drawing in the flour from the sides of the bowl. ',
      'Add the remaining milk and continue mixing to form a completely smooth batter. ',
      'In a separate bowl, whisk the egg whites, using an electric whisk, until stiff peaks form. ',
      'Using a large, metal spoon, gently fold the egg whites into the batter, being careful not to knock the air out.',
      'Put a large, nonstick frying pan over a medium-high heat and lightly brush with a little butter to grease. ',
      'Spoon 4 generous tbsp of batter into the pan to make 4 separate pancakes – space them out as they will spread a little. ',
      'Cook for 1 min, until bubbles rise to the surface, then turn and cook for a further 30 seconds – 1 min. ',
      'Transfer to a warm plate, covered with a tea towel. ',
      'Repeat to make 16 pancakes. ',
      'To serve, arrange 4 pancakes on each plate with some sliced avocado and tomatoes. ',
      'Top with a dollop of the lemon cream cheese and scatter with a little extra lemon zest. ',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  // Drinks List: 6 meals

  Meal(
    id: 'm60',
    categories: [
      'c6',
    ],
    title: 'Vegan Hot Chocolate ',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m60.jpg',
    duration: 10,
    ingredients: [
      '250ml oat milk-alternative',
      '1 cinnamon stick',
      '2 tbsp Sweet Freedom choc shot liquid chocolate',
      'Food Heaven heavenly whipped vegan cream, to serve',
      'Free From chocolate bar, to serve',
    ],
    steps: [
      'Heat oat milk with the cinnamon stick in a small saucepan over a medium heat, stirring, for 5 mins or until hot. ',
      'Stir in the Sweet Freedom Choc Shot Hot Chocolate until melted.',
      'Pour into a heatproof glass or mug and top with a squirt of cream.',
      'Garnish with the cinnamon stick and grate over some chocolate to decorate.',

    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm61',
    categories: [
      'c6',
    ],
    title: 'Toasted Barley and Honey Tea',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m61.jpg',
    duration: 10,
    ingredients: [
      '30g pearl barley',
      '2 tsp honey',
      'squeeze of fresh orange juice, plus 2 thin slices',
    ],
    steps: [
      'Rinse the pearl barley in a sieve, then rub dry in a clean tea towel. ',
      'Heat a small frying pan over a medium heat and add the barley. ',
      'Toast, stirring constantly, for 4-5 mins until deep golden brown and nutty-smelling, then remove from the heat and transfer to a teapot.',
      'Pour over 500ml boiling water and stir in the honey. ',
      'Allow to brew for 3-4 mins until golden, then pour into cups. ',
      'Add an orange slice and a squeeze of juice to each cup for a little extra zing. ',

    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm62',
    categories: [
      'c6',
    ],
    title: 'Salted Caramel Hot Chocolate',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m62.jpg',
    duration: 10,
    ingredients: [
      '450ml whole milk',
      '75g dark chocolate (at least 70% cocoa solids), chopped, plus a little extra grated chocolate to garnish',
      'pinch ground cinnamon',
      'pinch nutmeg',
      '3 tbsp Tesco Finest salted caramel dessert sauce',
      'pinch hot chilli powder',
      'pinch sea salt, or to taste (see tip)',
      '4-6 cinnamon sticks, to serve (optional)',
    ],
    steps: [
      'Put the milk in a saucepan and bring to a simmer over a gentle heat. ',
      'Remove from the heat and stir through the chocolate, cinnamon, nutmeg, salted caramel and chilli. ',
      'Stir until the chocolate has melted. ',
      'Add the sea salt, to taste. ',
      'Return to the heat, stirring, until it just starts to simmer.',
      'Pour into small cups. ',
      'Serve with the cinnamon sticks to use as stirrers, if using. ',
      'Sprinkle with the grated chocolate.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm63',
    categories: [
      'c6',
    ],
    title: 'Chai-spiced Tea',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m63.jpg',
    duration: 10,
    ingredients: [
      '2.5cm (1in) unpeeled ginger, sliced',
      '6 green cardamom pods',
      '2 cinnamon sticks',
      '8 cloves',
      '6 Darjeeling tea bags',
      '250ml milk',
      '100g golden caster sugar, or to taste',
    ],
    steps: [
      'Place the ginger and spices in a heavy-based saucepan and bruise with the end of a rolling pin to release their flavours.',
      'Add 1.5 litres (2 1/2 pints) cold water and bring to the boil, reduce the heat to low and simmer very gently for 10 minutes.',
      'Remove from the heat, add the 6 Darjeeling tea bags and leave to steep for 5 minutes.',
      'Remove the tea bags, add the milk and sugar to taste and return to the heat. ',
      'Bring back to a gentle simmer, whisking constantly to dissolve the sugar. ',
      'Strain into warmed cups and serve hot.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm64',
    categories: [
      'c6',
    ],
    title: 'Iced Latte',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m64.png',
    duration: 5,
    ingredients: [
      '2 espresso shots (60ml)',
      '2 tsp sugar, honey or maple syrup (to taste)',
      'ice',
      '100ml whole milk',

    ],
    steps: [
      'Mix the hot espresso with the sugar until it dissolves.',
      'Fill a glass with ice and stir in the sweetened coffee.',
      'Pour over the milk and stir until combined.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm65',
    categories: [
      'c6',
    ],
    title: 'Iced Tea',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
    'assets/m65.jpg',
    duration: 5,
    ingredients: [
      '4 teabags'
          '1 tbsp sugar (optional)'
          '1-2 lemons, sliced'
          'mint sprigs, to serve'
          'ice cubes, to serve'
    ],
    steps: [
      'Add the teabags, sugar (if using) and half the lemon slices (reserving the rest to serve) to a large heatproof jug or pitcher. ',
      'Pour over 1ltr just boiled water and leave to steep for 5 mins.',
      'Stir well, then discard the teabags and lemon slices and allow to cool to room temperature before transferring to the fridge to chill. ',
      'The tea will keep for 2-3 days covered in the fridge.',
      'When ready to serve, fill glasses with ice and the remaining lemon slices.',
      'Pour in the chilled tea and garnish with a sprig of mint.',

    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),


];





